name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  IMAGE_REPO: ghcr.io/elifesciences/enhanced-preprints-encoda

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: yarn
      - name: install dependencies
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run unit test
        run: yarn test --passWithNoTests
      - name: run integration test
        run: yarn test:integration
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and load test image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: prod
          tags: |
            ${{ env.IMAGE_REPO }}:test-${{ github.sha }}
  build-and-push:
    needs: [test, build-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "commit_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        id: build-push
        with:
          context: .
          cache-from: type=registry,ref=${{ env.IMAGE_REPO }}:build-cache
          cache-to: type=registry,ref=${{ env.IMAGE_REPO }}:build-cache,mode=max
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
      - name: Generate artefact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_REPO }}
          subject-digest: ${{ steps.build-push.outputs.digest }}
