name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  IMAGE_REPO: ghcr.io/elifesciences/enhanced-preprints-encoda

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and load test image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: tests
          load: true
          tags: |
            ${{ env.IMAGE_REPO }}:test-${{ github.sha }}
      - name: run lint
        run: docker run ${{ env.IMAGE_REPO }}:test-${{ github.sha }} yarn lint
      - name: run unit test
        run: docker run ${{ env.IMAGE_REPO }}:test-${{ github.sha }} yarn test --passWithNoTests
      - name: run integration test
        run: docker run ${{ env.IMAGE_REPO }}:test-${{ github.sha }} yarn test:integration --passWithNoTests
  build-and-push:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date --utc +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "commit_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: worker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
